# Generated by Django 5.2.5 on 2025-10-12 04:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
